Idea - Decentralization of Finance system
openBookmarkz/ideas pull request #9
Opened 2023-10-02 04:12 UTC by sahalhes

## Description of the idea

## Category

## Checklist

- [x ] I have clearly mentioned the creator of the idea, whether it's mine or someone else's.
- [x ] My entry adheres to the Docs style guide, ensuring consistency and readability.
- [x ] My changes do not generate any new warnings or errors.
- [x ] I have thoroughly checked my entries for misspellings and corrected them.
- [x ] I have made necessary updates to the documentation if my changes impact it.
- [x ] I have confirmed that my changes are not being pushed from my forked main branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making to keep the codebase organized and manageable.

2023-10-02 05:07 UTC, ATREAY requested changes
hey @sahalhes, I've requested for certain modifications. Kindly proceed with making those changes accordingly.

2023-10-02 05:07 UTC, ATREAY commented on ideaTemplate/ideas.md
> +
just the title should be in block letters not the description of it.

2023-10-02 05:07 UTC, ATREAY commented on ideaTemplate/ideas.md
> +
The same applies to the idea's title.

2023-10-02 05:07 UTC, ATREAY commented on ideaTemplate/ideas.md
> +Additiional Note from Author:
Just give it a quick spell check here

2023-10-02 05:07 UTC, ATREAY commented on ideaTemplate/ideas.md
> +Together, we can shape the future of finance for the better.
I think we can skip this sentence; it's a bit too vague.

2023-10-02 08:30 UTC, TusharPuranik requested changes
A lot of decentralized finance systems already exist, elaborate on how your idea differentiates from the rest.

2023-10-02 08:30 UTC, TusharPuranik commented on ideaTemplate/ideas.md
> +    - Future Finance System
Please modify the category here. It could be in the blockchain category.

2023-10-03 02:01 UTC, sahalhes commented
@ATREAY Hey I have resolved all the issues told by both you and @TusharPuranik . Kindly check and tell if there are any more changes required.

2023-10-03 04:18 UTC, ATREAY approved these changes
Hey @sahalhes, it looks good to me! Now, let's wait and see what the other reviewer thinks.

2023-10-03 09:18 UTC, TusharPuranik approved these changes
Looks good.

2023-10-03 09:21 UTC, merged

2023-10-03 09:23 UTC, ATREAY commented
Big thanks, @sahalhes! We really appreciate your contribution to openBookmarkz and for sharing your awesome idea with us. Your input means a lot to us and helps us grow. Keep those ideas coming!